// ===== PRODUCT DATABASE =====
// Add or modify products here
const products = [
    // ===== SUNGLASSES =====
    {
        id: 1,
        name: "Aviator Classic Gold",
        brand: "Ray-Ban",
        category: "sunglasses",
        gender: "unisex",
        color: "gold",
        price: 4500,
        oldPrice: 6000,
        image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=500",
        material: "Metal",
        size: "58-14-140",
        badge: "Bestseller",
        description: "Classic aviator design with UV400 protection. Polarized lenses."
    },
    {
        id: 2,
        name: "Wayfarer Black",
        brand: "Ray-Ban",
        category: "sunglasses",
        gender: "men",
        color: "black",
        price: 3800,
        oldPrice: 5000,
        image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=500",
        material: "Acetate",
        size: "54-18-145",
        badge: "Popular",
        description: "Iconic wayfarer style. Anti-glare coating included."
    },
    {
        id: 3,
        name: "Cat Eye Brown",
        brand: "Vogue",
        category: "sunglasses",
        gender: "women",
        color: "brown",
        price: 2800,
        oldPrice: 3500,
        image: "https://images.unsplash.com/photo-1577803645773-f96470509666?w=500",
        material: "Plastic",
        size: "55-16-140",
        badge: "New",
        description: "Stylish cat-eye design perfect for women. Trendy & comfortable."
    },
    {
        id: 4,
        name: "Sports Wraparound",
        brand: "Oakley",
        category: "sunglasses",
        gender: "men",
        color: "black",
        price: 5500,
        oldPrice: 7000,
        image: "https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=500",
        material: "Polycarbonate",
        size: "60-15-130",
        badge: "Sports",
        description: "Perfect for cycling, running and outdoor sports."
    },
    {
        id: 5,
        name: "Round Vintage Silver",
        brand: "Fastrack",
        category: "sunglasses",
        gender: "unisex",
        color: "silver",
        price: 1200,
        oldPrice: 1800,
        image: "https://images.unsplash.com/photo-1556306535-0f09a537f0a3?w=500",
        material: "Metal",
        size: "52-20-145",
        description: "Retro round frame, lightweight and stylish."
    },
    {
        id: 6,
        name: "Polarized Blue Tint",
        brand: "Carrera",
        category: "sunglasses",
        gender: "men",
        color: "blue",
        price: 6500,
        oldPrice: 8500,
        image: "https://images.unsplash.com/photo-1508296695146-257a814070b4?w=500",
        material: "Acetate",
        size: "57-17-145",
        description: "Premium polarized lens with blue tint."
    },
    
    // ===== EYEGLASSES =====
    {
        id: 7,
        name: "Rectangle Frame",
        brand: "Titan",
        category: "eyeglasses",
        gender: "men",
        color: "black",
        price: 2200,
        oldPrice: 3000,
        image: "https://images.unsplash.com/photo-1574258495973-f010dfbb5371?w=500",
        material: "Acetate",
        size: "52-17-140",
        badge: "Trending",
        description: "Professional rectangular frame for daily wear."
    },
    {
        id: 8,
        name: "Round Tortoise",
        brand: "Vogue",
        category: "eyeglasses",
        gender: "unisex",
        color: "brown",
        price: 1800,
        oldPrice: 2500,
        image: "https://images.unsplash.com/photo-1591076482161-42ce6da69f67?w=500",
        material: "Acetate",
        size: "48-22-145",
        description: "Classic tortoise shell pattern. Lightweight."
    },
    {
        id: 9,
        name: "Cat Eye Pink",
        brand: "Vogue",
        category: "eyeglasses",
        gender: "women",
        color: "gold",
        price: 2500,
        oldPrice: 3200,
        image: "https://images.unsplash.com/photo-1582142306909-195724d33ffc?w=500",
        material: "Metal",
        size: "53-15-140",
        badge: "Hot",
        description: "Elegant cat eye with rose gold finish."
    },
    {
        id: 10,
        name: "Square Half Rim",
        brand: "Titan",
        category: "eyeglasses",
        gender: "men",
        color: "silver",
        price: 1500,
        oldPrice: 2000,
        image: "https://images.unsplash.com/photo-1633621641966-23836fcafd7b?w=500",
        material: "Metal",
        size: "54-18-140",
        description: "Half rim design, light & comfortable."
    },
    {
        id: 11,
        name: "Round Gold Vintage",
        brand: "Ray-Ban",
        category: "eyeglasses",
        gender: "unisex",
        color: "gold",
        price: 3500,
        oldPrice: 4500,
        image: "https://images.unsplash.com/photo-1602699269437-cb288917b78d?w=500",
        material: "Metal",
        size: "50-21-145",
        description: "Vintage round metal frame, premium quality."
    },
    {
        id: 12,
        name: "Oval Brown Acetate",
        brand: "Fastrack",
        category: "eyeglasses",
        gender: "women",
        color: "brown",
        price: 950,
        oldPrice: 1400,
        image: "https://images.unsplash.com/photo-1638784626483-c0c5b8b9d1d5?w=500",
        material: "Acetate",
        size: "51-17-140",
        badge: "Budget",
        description: "Budget-friendly oval design for women."
    },
    
    // ===== CONTACT LENSES =====
    {
        id: 13,
        name: "Daily Disposable - Pack of 30",
        brand: "Bausch & Lomb",
        category: "contact",
        gender: "unisex",
        color: "transparent",
        price: 1500,
        oldPrice: 1800,
        image: "https://images.unsplash.com/photo-1609902726285-00668009f004?w=500",
        material: "Hydrogel",
        size: "Standard",
        badge: "Hygiene+",
        description: "Daily disposable contact lenses. Fresh pair every day."
    },
    {
        id: 14,
        name: "Monthly Lenses - Pack of 2",
        brand: "Acuvue",
        category: "contact",
        gender: "unisex",
        color: "transparent",
        price: 1200,
        oldPrice: 1500,
        image: "https://images.unsplash.com/photo-1587400416172-a48a96b1d8aa?w=500",
        material: "Silicone Hydrogel",
        size: "Standard",
        description: "Monthly disposable, comfortable for long wear."
    },
    {
        id: 15,
        name: "Color Contact - Blue",
        brand: "FreshLook",
        category: "contact",
        gender: "women",
        color: "blue",
        price: 800,
        oldPrice: 1100,
        image: "https://images.unsplash.com/photo-1612817288484-6f916006741a?w=500",
        material: "Hydrogel",
        size: "Standard",
        badge: "Colored",
        description: "Beautiful blue colored contact lenses."
    },
    
    // ===== KIDS =====
    {
        id: 16,
        name: "Kids Round Blue",
        brand: "Fastrack Kids",
        category: "kids",
        gender: "kids",
        color: "blue",
        price: 1100,
        oldPrice: 1500,
        image: "https://images.unsplash.com/photo-1610563166150-b34df4f3bcd6?w=500",
        material: "Flexible Plastic",
        size: "46-15-125",
        badge: "Kid-Safe",
        description: "Safe, flexible frame for kids. Anti-break design."
    },
    {
        id: 17,
        name: "Kids Square Black",
        brand: "Titan Kids",
        category: "kids",
        gender: "kids",
        color: "black",
        price: 900,
        oldPrice: 1300,
        image: "https://images.unsplash.com/photo-1604881991720-f91add269bed?w=500",
        material: "TR-90",
        size: "44-16-125",
        description: "Durable kids frame. Suitable for ages 5-12."
    },
    {
        id: 18,
        name: "Kids Sports Goggle",
        brand: "Sporty Kids",
        category: "kids",
        gender: "kids",
        color: "black",
        price: 1500,
        oldPrice: 2000,
        image: "https://images.unsplash.com/photo-1583743089695-4b816a340f82?w=500",
        material: "Rubber + Plastic",
        size: "48-16-125",
        badge: "Sports",
        description: "Sports goggles with elastic band for active kids."
    }
];

// WhatsApp number (centralized)
const WHATSAPP_NUMBER = "919555860408";
const SHOP_NAME = "Puja Opticals";
const SHOP_ADDRESS = "Mohanlalganj, Lucknow";
